server:
  port: 8081
  
  
spring:
  jpa:
    hibernate:
      ddl-auto: update
    
  datasource:
    url: jdbc:mysql://localhost:3306/customer??characterEncoding=utf8&useSSL=true
    username: apple
    password: apple